### ISSUE TITLE
Features and Tasks for v0.1

### ISSUE THREAD

**Issue by hakobera** [tumugi/tumugi#4]
This is meta issue for Tumugi v0.1.0 release.
- [x] Dependency resolution #3 
- [x] DSL support #3
- [x] Task inherit support #5
- [x] Concurrent task execution #7
- [x] DAG rendering using dotfile and Graphviz #6
- [x] Retry #8
- Write document
  - [x] Setup Github Pages https://tumugi.github.io/
  - [x] Write Getting started

**Comment by hakobera** [comment]
Finally first version of Tumugi released! 
https://rubygems.org/gems/tumugi
